# Central Tendency

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# Load the dataset1
dataset1 = pd.read_csv('analyzed_application_data.csv')

# find mean, median, mode find IQR(interquartile Range), min and max ans lesser and greater IQR!

In [3]:
# Create a copy of the original dataset for comparison
original_dataset = dataset1.copy()

# Create a DataFrame to store descriptive statistics
descriptive = pd.DataFrame(index=['Mean', 'Median', 'Mode', 'Q1:25%', 'Q2:50%', 'Q3:75%', 'Q4:100%', 'IQR', 'Lesser IQR', 'Greater IQR', 'min', 'max'], columns=dataset1.columns)

# Calculate additional statistics
for columnName in dataset1.columns:
    descriptive.loc["Mean", columnName] = dataset1[columnName].mean()
    descriptive.loc["Median", columnName] = dataset1[columnName].median()
    descriptive.loc["Mode", columnName] = dataset1[columnName].mode()[0]
    descriptive.loc['Q1:25%', columnName] = dataset1[columnName].quantile(0.25)
    descriptive.loc['Q2:50%', columnName] = dataset1[columnName].quantile(0.50)
    descriptive.loc['Q3:75%', columnName] = dataset1[columnName].quantile(0.75)
    descriptive.loc['min', columnName] = dataset1[columnName].min()
    descriptive.loc['max', columnName] = dataset1[columnName].max()
    descriptive.loc['Q4:100%', columnName] = dataset1[columnName].max()  # Add Q4:100% here

    iqr = descriptive.loc['Q3:75%', columnName] - descriptive.loc['Q1:25%', columnName]
    descriptive.loc['IQR', columnName] = iqr
    descriptive.loc['Lesser IQR', columnName] = descriptive.loc['Q1:25%', columnName] - 1.5 * iqr
    descriptive.loc['Greater IQR', columnName] = descriptive.loc['Q3:75%', columnName] + 1.5 * iqr

In [4]:
descriptive

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
Mean,278180.518577,0.080729,0.095213,0.341669,0.340108,0.693673,0.417052,168797.919297,599025.999706,27108.573909,...,0.00813,0.000595,0.000507,0.000335,0.005538,0.006055,0.029723,0.231293,0.229631,1.778463
Median,278202.0,0.0,0.0,0.0,0.0,1.0,0.0,147150.0,513531.0,24903.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
Mode,100002,0,0,0,0,1,0,135000.0,450000.0,9000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
Q1:25%,189145.5,0.0,0.0,0.0,0.0,0.0,0.0,112500.0,270000.0,16524.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
Q2:50%,278202.0,0.0,0.0,0.0,0.0,1.0,0.0,147150.0,513531.0,24903.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
Q3:75%,367142.5,0.0,0.0,1.0,1.0,1.0,1.0,202500.0,808650.0,34596.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0
Q4:100%,456255,1,1,2,1,1,19,117000000.0,4050000.0,258025.5,...,1,1,1,1,4.0,9.0,8.0,27.0,261.0,25.0
IQR,177997.0,0.0,0.0,1.0,1.0,1.0,1.0,90000.0,538650.0,18072.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
Lesser IQR,-77850.0,0.0,0.0,-1.5,-1.5,-1.5,-1.5,-22500.0,-537975.0,-10584.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-2.0
Greater IQR,634138.0,0.0,0.0,2.5,2.5,2.5,2.5,337500.0,1616625.0,61704.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0
min,100002,0,0,0,0,0,0,25650.0,45000.0,1615.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
max,456255,1,1,2,1,1,19,117000000.0,4050000.0,258025.5,...,1,1,1,1,4.0,9.0,8.0,27.0,261.0,25.0

# Check Outliers

In [5]:
lesser = []
greater = []
# Check for outliers
for columnName in dataset1:
    if  descriptive.loc['Lesser IQR', columnName] > descriptive.loc['min', columnName]:
        lesser.append(columnName)

    if  descriptive.loc['Greater IQR', columnName] < descriptive.loc['max', columnName]:
        greater.append(columnName)

In [6]:
lesser

['NAME_TYPE_SUITE',
 'NAME_HOUSING_TYPE',
 'DAYS_EMPLOYED',
 'DAYS_REGISTRATION',
 'OWN_CAR_AGE',
 'FLAG_MOBIL',
 'FLAG_EMP_PHONE',
 'FLAG_CONT_MOBILE',
 'OCCUPATION_TYPE',
 'REGION_RATING_CLIENT',
 'REGION_RATING_CLIENT_W_CITY',
 'HOUR_APPR_PROCESS_START',
 'EXT_SOURCE_1',
 'EXT_SOURCE_3',
 'APARTMENTS_AVG',
 'BASEMENTAREA_AVG',
 'YEARS_BEGINEXPLUATATION_AVG',
 'YEARS_BUILD_AVG',
 'COMMONAREA_AVG',
 'ENTRANCES_AVG',
 'FLOORSMAX_AVG',
 'FLOORSMIN_AVG',
 'LANDAREA_AVG',
 'LIVINGAPARTMENTS_AVG',
 'LIVINGAREA_AVG',
 'NONLIVINGAREA_AVG',
 'APARTMENTS_MODE',
 'BASEMENTAREA_MODE',
 'YEARS_BEGINEXPLUATATION_MODE',
 'YEARS_BUILD_MODE',
 'COMMONAREA_MODE',
 'ENTRANCES_MODE',
 'FLOORSMAX_MODE',
 'FLOORSMIN_MODE',
 'LANDAREA_MODE',
 'LIVINGAPARTMENTS_MODE',
 'LIVINGAREA_MODE',
 'NONLIVINGAREA_MODE',
 'APARTMENTS_MEDI',
 'BASEMENTAREA_MEDI',
 'YEARS_BEGINEXPLUATATION_MEDI',
 'YEARS_BUILD_MEDI',
 'COMMONAREA_MEDI',
 'ENTRANCES_MEDI',
 'FLOORSMAX_MEDI',
 'FLOORSMIN_MEDI',
 'LANDAREA_MEDI',
 'LIVINGAPARTMENTS_MEDI',
 'LIVINGAREA_MEDI',
 'NONLIVINGAREA_MEDI',
 'FONDKAPREMONT_MODE',
 'TOTALAREA_MODE',
 'WALLSMATERIAL_MODE',
 'DAYS_LAST_PHONE_CHANGE']

In [7]:
greater

['TARGET',
 'NAME_CONTRACT_TYPE',
 'CNT_CHILDREN',
 'AMT_INCOME_TOTAL',
 'AMT_CREDIT',
 'AMT_ANNUITY',
 'AMT_GOODS_PRICE',
 'NAME_FAMILY_STATUS',
 'NAME_HOUSING_TYPE',
 'REGION_POPULATION_RELATIVE',
 'DAYS_EMPLOYED',
 'OWN_CAR_AGE',
 'FLAG_WORK_PHONE',
 'FLAG_EMAIL',
 'OCCUPATION_TYPE',
 'CNT_FAM_MEMBERS',
 'REGION_RATING_CLIENT',
 'REGION_RATING_CLIENT_W_CITY',
 'HOUR_APPR_PROCESS_START',
 'REG_REGION_NOT_LIVE_REGION',
 'REG_REGION_NOT_WORK_REGION',
 'LIVE_REGION_NOT_WORK_REGION',
 'REG_CITY_NOT_LIVE_CITY',
 'REG_CITY_NOT_WORK_CITY',
 'LIVE_CITY_NOT_WORK_CITY',
 'EXT_SOURCE_1',
 'APARTMENTS_AVG',
 'BASEMENTAREA_AVG',
 'YEARS_BEGINEXPLUATATION_AVG',
 'YEARS_BUILD_AVG',
 'COMMONAREA_AVG',
 'ELEVATORS_AVG',
 'ENTRANCES_AVG',
 'FLOORSMAX_AVG',
 'FLOORSMIN_AVG',
 'LANDAREA_AVG',
 'LIVINGAPARTMENTS_AVG',
 'LIVINGAREA_AVG',
 'NONLIVINGAPARTMENTS_AVG',
 'NONLIVINGAREA_AVG',
 'APARTMENTS_MODE',
 'BASEMENTAREA_MODE',
 'YEARS_BEGINEXPLUATATION_MODE',
 'YEARS_BUILD_MODE',
 'COMMONAREA_MODE',
 'ELEVATORS_MODE',
 'ENTRANCES_MODE',
 'FLOORSMAX_MODE',
 'FLOORSMIN_MODE',
 'LANDAREA_MODE',
 'LIVINGAPARTMENTS_MODE',
 'LIVINGAREA_MODE',
 'NONLIVINGAPARTMENTS_MODE',
 'NONLIVINGAREA_MODE',
 'APARTMENTS_MEDI',
 'BASEMENTAREA_MEDI',
 'YEARS_BEGINEXPLUATATION_MEDI',
 'YEARS_BUILD_MEDI',
 'COMMONAREA_MEDI',
 'ELEVATORS_MEDI',
 'ENTRANCES_MEDI',
 'FLOORSMAX_MEDI',
 'FLOORSMIN_MEDI',
 'LANDAREA_MEDI',
 'LIVINGAPARTMENTS_MEDI',
 'LIVINGAREA_MEDI',
 'NONLIVINGAPARTMENTS_MEDI',
 'NONLIVINGAREA_MEDI',
 'FONDKAPREMONT_MODE',
 'HOUSETYPE_MODE',
 'TOTALAREA_MODE',
 'WALLSMATERIAL_MODE',
 'EMERGENCYSTATE_MODE',
 'OBS_30_CNT_SOCIAL_CIRCLE',
 'DEF_30_CNT_SOCIAL_CIRCLE',
 'OBS_60_CNT_SOCIAL_CIRCLE',
 'DEF_60_CNT_SOCIAL_CIRCLE',
 'FLAG_DOCUMENT_2',
 'FLAG_DOCUMENT_4',
 'FLAG_DOCUMENT_5',
 'FLAG_DOCUMENT_6',
 'FLAG_DOCUMENT_7',
 'FLAG_DOCUMENT_8',
 'FLAG_DOCUMENT_9',
 'FLAG_DOCUMENT_10',
 'FLAG_DOCUMENT_11',
 'FLAG_DOCUMENT_12',
 'FLAG_DOCUMENT_13',
 'FLAG_DOCUMENT_14',
 'FLAG_DOCUMENT_15',
 'FLAG_DOCUMENT_16',
 'FLAG_DOCUMENT_17',
 'FLAG_DOCUMENT_18',
 'FLAG_DOCUMENT_19',
 'FLAG_DOCUMENT_20',
 'FLAG_DOCUMENT_21',
 'AMT_REQ_CREDIT_BUREAU_HOUR',
 'AMT_REQ_CREDIT_BUREAU_DAY',
 'AMT_REQ_CREDIT_BUREAU_WEEK',
 'AMT_REQ_CREDIT_BUREAU_MON',
 'AMT_REQ_CREDIT_BUREAU_QRT',
 'AMT_REQ_CREDIT_BUREAU_YEAR']

In [8]:
# Replace outliers with min or max values
for columnName in lesser:
    dataset1.loc[dataset1[columnName] < descriptive.loc['Lesser IQR', columnName], columnName] = descriptive.loc['Lesser IQR', columnName]

for columnName in greater:
    dataset1.loc[dataset1[columnName] > descriptive.loc['Greater IQR', columnName], columnName] = descriptive.loc['Greater IQR', columnName]

C:\Users\ELCOT\AppData\Local\Temp\ipykernel_9800\603978393.py:3: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '-6466.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  dataset1.loc[dataset1[columnName] < descriptive.loc['Lesser IQR', columnName], columnName] = descriptive.loc['Lesser IQR', columnName]
C:\Users\ELCOT\AppData\Local\Temp\ipykernel_9800\603978393.py:3: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  dataset1.loc[dataset1[columnName] < descriptive.loc['Lesser IQR', columnName], columnName] = descriptive.loc['Lesser IQR', columnName]
C:\Users\ELCOT\AppData\Local\Temp\ipykernel_9800\603978393.py:6: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  dataset1.loc[dataset1[columnName] > descriptive.loc['Greater IQR', columnName], columnName] = descriptive.loc['Greater IQR', columnName]
C:\Users\ELCOT\AppData\Local\Temp\ipykernel_9800\603978393.py:6: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '3.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  dataset1.loc[dataset1[columnName] > descriptive.loc['Greater IQR', columnName], columnName] = descriptive.loc['Greater IQR', columnName]

In [9]:
# Create a copy of the original dataset for comparison
original_dataset = dataset1.copy()

# Create a DataFrame to store descriptive statistics
descriptive = pd.DataFrame(index=['Mean', 'Median', 'Mode', 'Q1:25%', 'Q2:50%', 'Q3:75%', 'Q4:100%', 'IQR', 'Lesser IQR', 'Greater IQR', 'min', 'max'], columns=dataset1.columns)

# Calculate additional statistics
for columnName in dataset1.columns:
    descriptive.loc["Mean", columnName] = dataset1[columnName].mean()
    descriptive.loc["Median", columnName] = dataset1[columnName].median()
    descriptive.loc["Mode", columnName] = dataset1[columnName].mode()[0]
    descriptive.loc['Q1:25%', columnName] = dataset1[columnName].quantile(0.25)
    descriptive.loc['Q2:50%', columnName] = dataset1[columnName].quantile(0.50)
    descriptive.loc['Q3:75%', columnName] = dataset1[columnName].quantile(0.75)
    descriptive.loc['min', columnName] = dataset1[columnName].min()
    descriptive.loc['max', columnName] = dataset1[columnName].max()
    descriptive.loc['Q4:100%', columnName] = dataset1[columnName].max()  # Add Q4:100% here

    iqr = descriptive.loc['Q3:75%', columnName] - descriptive.loc['Q1:25%', columnName]
    descriptive.loc['IQR', columnName] = iqr
    descriptive.loc['Lesser IQR', columnName] = descriptive.loc['Q1:25%', columnName] - 1.5 * iqr
    descriptive.loc['Greater IQR', columnName] = descriptive.loc['Q3:75%', columnName] + 1.5 * iqr

In [10]:
descriptive

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
Mean,278180.518577,0.0,0.0,0.341669,0.340108,0.693673,0.407455,162626.947877,592313.037054,26797.743219,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.738175
Median,278202.0,0.0,0.0,0.0,0.0,1.0,0.0,147150.0,513531.0,24903.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
Mode,100002,0,0,0,0,1,0.0,135000.0,450000.0,61704.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
Q1:25%,189145.5,0.0,0.0,0.0,0.0,0.0,0.0,112500.0,270000.0,16524.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
Q2:50%,278202.0,0.0,0.0,0.0,0.0,1.0,0.0,147150.0,513531.0,24903.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
Q3:75%,367142.5,0.0,0.0,1.0,1.0,1.0,1.0,202500.0,808650.0,34596.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0
Q4:100%,456255,0,0,2,1,1,2.5,337500.0,1616625.0,61704.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,6.0
IQR,177997.0,0.0,0.0,1.0,1.0,1.0,1.0,90000.0,538650.0,18072.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
Lesser IQR,-77850.0,0.0,0.0,-1.5,-1.5,-1.5,-1.5,-22500.0,-537975.0,-10584.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-2.0
Greater IQR,634138.0,0.0,0.0,2.5,2.5,2.5,2.5,337500.0,1616625.0,61704.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0
min,100002,0,0,0,0,0,0.0,25650.0,45000.0,1615.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
max,456255,0,0,2,1,1,2.5,337500.0,1616625.0,61704.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,6.0

In [11]:
lesser = []
greater = []
# Check for outliers
for columnName in dataset1:
    if  descriptive.loc['Lesser IQR', columnName] > descriptive.loc['min', columnName]:
        lesser.append(columnName)

    if  descriptive.loc['Greater IQR', columnName] < descriptive.loc['max', columnName]:
        greater.append(columnName)

In [12]:
lesser

[]

In [13]:
greater

[]